# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-23 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='krsturl',
            name='shortcode',
            field=models.CharField(default='666', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
